"""update tables relationships

Revision ID: ef5580342f45
Revises: ebaa35b2ff9c
Create Date: 2025-12-20 09:22:07.723882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef5580342f45'
down_revision: Union[str, Sequence[str], None] = 'ebaa35b2ff9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_bills_user_id'), 'bills', ['user_id'], unique=False)
    op.create_foreign_key(None, 'bills', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.add_column('categories', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_category_name', 'categories', ['user_id', 'name'])
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint('uq_user_category_name', 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_column('categories', 'user_id')
    op.drop_constraint(None, 'bills', type_='foreignkey')
    op.drop_index(op.f('ix_bills_user_id'), table_name='bills')
    op.drop_column('bills', 'user_id')
    # ### end Alembic commands ###
