"""Delete cascade

Revision ID: abaac5f4b323
Revises: 1f5348c75a9f
Create Date: 2025-12-28 20:54:21.900884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abaac5f4b323'
down_revision: Union[str, Sequence[str], None] = '1f5348c75a9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.drop_constraint(
        "bills_user_id_fkey",
        "bills",
        type_="foreignkey"
    )
    op.create_foreign_key(
        "bills_user_id_fkey",
        "bills",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE"
    )
    op.drop_constraint(
        "categories_user_id_fkey",
        "categories",
        type_="foreignkey"
    )
    op.create_foreign_key(
        "categories_user_id_fkey",
        "categories",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE"
    )
    op.drop_constraint(
        "refresh_tokens_user_id_fkey",
        "refresh_tokens",
        type_="foreignkey"
    )
    op.create_foreign_key(
        "refresh_tokens_user_id_fkey",
        "refresh_tokens",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    # ### end Alembic commands ###
